"""add storage_path

Revision ID: e3f529450c35
Revises: 2122589e3bd0
Create Date: 2026-03-04 15:53:40.895438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f529450c35'
down_revision: Union[str, None] = '2122589e3bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "documents",
        sa.Column("storage_path", sa.String(length=500), nullable=True),
    )
    op.execute("UPDATE documents SET storage_path = '' WHERE storage_path IS NULL")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'storage_path')
    # ### end Alembic commands ###
